### ISSUE TITLE
Al momento de ejecutar la aplicación...

### ISSUE THREAD

**Issue by Autinfit** [Autinfit/PingPong#11]
La bola del juego no se movía hacia ambos lados, quizá lo más probable es que corrija en la sección de declaración de variables para que esto pueda funcionar.

**Comment by MARSFOREVER472** [comment]
Justamente, creo que en la sección en la cuál habías dicho, deberías modificar la velocidad de la bola hacia ambos lados, no dejarlo por defecto en 0, ya que con esto no se podía mover dicha bola.

Espero te sirva de ayuda, estimado!

**Comment by Autinfit** [comment]
Muchas gracias, estimado MARSFOREVER472, de inmediato lo voy a arreglar!

Saludos!
