### ISSUE TITLE
Evento mal escrito...

### ISSUE THREAD

**Issue by Autinfit** [Autinfit/PingPong#2]
Se me agregó otro evento al escribir en este mismo campo, sin embargo, había errores al corregirlo, si es que mi afiliado me pueda ayudar con esto!

Espero su respuesta, MARSFOREVER472!

**Comment by MARSFOREVER472** [comment]
Estimado, en el mismo archivo de dónde surgió el error, aparecía el mismo evento que agregaste, pero eso sí, deberías corregir solamente la palabra EventarSoltarTeclas por Evento.

Espero te sirva de ayuda, Estimado!

**Comment by Autinfit** [comment]
Muchas gracias, estimado, no sabía de que se agregó otro evento para corregir este problema.

Saludos!
